# .github/workflows/call-semantic-release.yml
name: Call Central Semantic Release Workflow

on:
  workflow_dispatch:

jobs:
  call-semantic-release:
    uses: l-s-a-s-h-a-l/workflows/blob/main/.github/workflows/semantic-release.yml@main
    with:
      node_version: '18'
      github_token: ${{ secrets.GH_TOKEN }}
